//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.28 at 08:18:10 AM CET 
//


package at.bva.fsw_poc.simulation.currencyconverter;


public class Response {

    protected double amount;
    protected Code currencyCode;

    public double getAmount() {
        return amount;
    }

    public void setAmount(double value) {
        this.amount = value;
    }

    public Code getCurrencyCode() {
        return currencyCode;
    }

    public void setCurrencyCode(Code value) {
        this.currencyCode = value;
    }

}
