//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 09:04:57 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eap5ejb2.fsw_poc.bva.at/")
package at.bva.fsw_poc.eap5ejb2;
